baseURL = "https://TTMos482.github.io/"
languageCode = "zh-CN"
title = "日记本"
theme = "ananke"

[params]
  description = "记录每日思考"
  showReadingTime = true

[[menu.main]]
  name = "首页"
  url = "/"
  weight = 1

[[menu.main]]
  name = "所有文章"
  url = "/posts/"
  weight = 2
